# ---------------------------------------------------------------------------
# AMI
# ---------------------------------------------------------------------------

# Only looked up when no ami_id is passed in.
data "aws_ami" "ubuntu" {
  count = var.ami_id == null ? 1 : 0

  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

locals {
  ami_id = var.ami_id != null ? var.ami_id : data.aws_ami.ubuntu[0].id
}

# ---------------------------------------------------------------------------
# SSH key pair, generated by Terraform. The private key is written locally
# (gitignored via *.pem) and is ALSO stored in Terraform state.
# ---------------------------------------------------------------------------

resource "tls_private_key" "this" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "this" {
  key_name   = "${var.name}-key"
  public_key = tls_private_key.this.public_key_openssh

  tags = { Name = "${var.name}-key" }
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.this.private_key_openssh
  filename        = var.private_key_path
  file_permission = "0400"
}

# ---------------------------------------------------------------------------
# Security group. Rules are separate resources (not inline blocks) so that
# other modules - e.g. the ALB - can attach their own rules to this group
# without Terraform fighting over who owns the rule list.
# ---------------------------------------------------------------------------

resource "aws_security_group" "this" {
  name        = "${var.name}-ec2-sg"
  description = "Web instance"
  vpc_id      = var.vpc_id

  tags = { Name = "${var.name}-ec2-sg" }
}

resource "aws_vpc_security_group_ingress_rule" "ssh" {
  security_group_id = aws_security_group.this.id
  description       = "SSH from allowed_ssh_cidr"
  ip_protocol       = "tcp"
  from_port         = 22
  to_port           = 22
  cidr_ipv4         = var.allowed_ssh_cidr
}

resource "aws_vpc_security_group_egress_rule" "all" {
  security_group_id = aws_security_group.this.id
  description       = "All outbound (apt, updates)"
  ip_protocol       = "-1"
  cidr_ipv4         = "0.0.0.0/0"
}

# ---------------------------------------------------------------------------
# Instance
# ---------------------------------------------------------------------------

resource "aws_instance" "this" {
  ami                    = local.ami_id
  instance_type          = var.instance_type
  subnet_id              = var.subnet_id
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.this.id]

  user_data = <<-EOT
    #!/bin/bash
    set -euo pipefail
    apt-get update -y
    apt-get install -y nginx
    echo "<h1>${var.name} - deployed by Terraform</h1>" > /var/www/html/index.html
    systemctl enable nginx
    systemctl restart nginx
  EOT

  tags = { Name = "${var.name}-web" }
}
